### ISSUE TITLE
Adjust filterer to handle meta objects

### ISSUE THREAD

**Issue by rsumilang** [wb-crowdfusion/wb-amp#3]
When a meta object is passed in, the test will always return true when typecasting. The filterer should check for a metaobject and handle the value when a boolean is not passed in.

**Comment by gdbrown** [comment]
let's also use php filter_var to catch 1/0, on/off, true/false strings.

**Comment by rsumilang** [comment]
Fixed in https://github.com/wb-crowdfusion/wb-amp/pull/4
